### ISSUE TITLE
/author/id//liked crashing on Heroku

### ISSUE THREAD

**Issue by debecerra** [CMPUT404F21TEAM/social-distribution#198]
```
2021-11-24T14:37:31.241343+00:00 app[web.1]: Cannot query "Diego": Must be "PostLike" instance.
2021-11-24T14:37:31.241364+00:00 app[web.1]: Traceback (most recent call last):
2021-11-24T14:37:31.241367+00:00 app[web.1]: File "/app/code/api/views.py", line 190, in get
2021-11-24T14:37:31.241369+00:00 app[web.1]: authorLikedPosts = LocalPost.objects.filter(likes__exact=author)
2021-11-24T14:37:31.241370+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
2021-11-24T14:37:31.241370+00:00 app[web.1]: return getattr(self.get_queryset(), name)(*args, **kwargs)
2021-11-24T14:37:31.241376+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/django/db/models/query.py", line 941, in filter
2021-11-24T14:37:31.241376+00:00 app[web.1]: return self._filter_or_exclude(False, args, kwargs)
2021-11-24T14:37:31.241376+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/django/db/models/query.py", line 961, in _filter_or_exclude
2021-11-24T14:37:31.241376+00:00 app[web.1]: clone._filter_or_exclude_inplace(negate, args, kwargs)
2021-11-24T14:37:31.241377+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/django/db/models/query.py", line 968, in _filter_or_exclude_inplace
2021-11-24T14:37:31.241377+00:00 app[web.1]: self._query.add_q(Q(*args, **kwargs))
2021-11-24T14:37:31.241377+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1393, in add_q
2021-11-24T14:37:31.241378+00:00 app[web.1]: clause, _ = self._add_q(q_object, self.used_aliases)
2021-11-24T14:37:31.241378+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1412, in _add_q
2021-11-24T14:37:31.241378+00:00 app[web.1]: child_clause, needed_inner = self.build_filter(
2021-11-24T14:37:31.241378+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1320, in build_filter
2021-11-24T14:37:31.241378+00:00 app[web.1]: self.check_related_objects(join_info.final_field, value, join_info.opts)
2021-11-24T14:37:31.241379+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1147, in check_related_objects
2021-11-24T14:37:31.241379+00:00 app[web.1]: self.check_query_object_type(value, opts, field)
2021-11-24T14:37:31.241379+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1128, in check_query_object_type
2021-11-24T14:37:31.241380+00:00 app[web.1]: raise ValueError(
2021-11-24T14:37:31.241380+00:00 app[web.1]: ValueError: Cannot query "Diego": Must be "PostLike" instance.
2021-11-24T14:37:31.241593+00:00 app[web.1]: Internal Server Error: /api/author/4/liked
2021-11-24T14:37:31.241610+00:00 app[web.1]: Internal Server Error: /api/author/4/liked

```

**Comment by olivier-vadiaval** [comment]
Related to #210 and #248
